/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Boxes: typeof import('./src/components/Boxes.vue')['default']
    Confetti: typeof import('./src/components/Confetti.vue')['default']
    Edit: typeof import('./src/components/Edit.vue')['default']
    Game: typeof import('./src/components/Game.vue')['default']
    Map: typeof import('./src/components/Map.vue')['default']
    Mines: typeof import('./src/components/Mines.vue')['default']
    Normal: typeof import('./src/components/Normal.vue')['default']
    OverMan: typeof import('./src/components/OverMan.vue')['default']
    Player: typeof import('./src/components/Player.vue')['default']
    SelectLevel: typeof import('./src/components/SelectLevel.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    Wall: typeof import('./src/components/Wall.vue')['default']
  }
}
