/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Box: typeof import('./src/components/Box.vue')['default']
    Boxes: typeof import('./src/components/Boxes.vue')['default']
    Confetti: typeof import('./src/components/Confetti.vue')['default']
    Game: typeof import('./src/components/Game.vue')['default']
    Grid: typeof import('./src/components/Grid.vue')['default']
    Map: typeof import('./src/components/Map.vue')['default']
    Mines: typeof import('./src/components/Mines.vue')['default']
    Normal: typeof import('./src/components/Normal.vue')['default']
    OverMan: typeof import('./src/components/OverMan.vue')['default']
    Player: typeof import('./src/components/Player.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
  }
}
